---
- name: Add MongoDB public GPC Key
  apt_key: url=hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add MongoDB stable repository (Ubuntu)
  apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  when: ansible_distribution == "Ubuntu" 

- name: run the equivalent of "apt-get update" as a separate step
  apt: update_cache=yes

- name: MongoDB | Install latest MongoDB release
  apt: name=mongodb-org state=present force=yes

- name: MongoDB | Create default configuration template
  template:
    src=mongodb.conf.tpl
    dest=/etc/mongodb.conf
    owner=root group=root mode=0644
  notify:
    - mongodb-restart

- name: MongoDB | Insure deamon is running correctly
  service: name=mongodb state=started