---
- name: Include variables
  include_vars: "main.yml"

- name: Add keys authenticity
  apt_key:
    keyserver: "{{ url_apt_key }}"
    id: "{{ id_apt_key }}"

- name: Ubuntu | Add source sources
  apt_repository: repo='{{ mongodb_repository }}' update_cache=yes

- name: Ubuntu | Install Packages
  apt: pkg={{ item }} update_cache=yes
  with_items: "{{ mongodb_packages }}"

- name: MongoDB | Create default configuration template
  template:
    src=mongodb.conf.tpl
    dest=/etc/mongodb.conf
    owner=root group=root mode=0644
  notify:
    - restart mongod